version: '3.8'
services:
  metabase:
    image: metabase/metabase:latest
    container_name: metabase
    restart: unless-stopped
    tty: true
    volumes:
      - ./plugins:/plugins
    ports:
      - "3000:3000"